Models/APIModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace welcome_to_web.Models
{
    public class APIModel
    {
        public string Name { get; set; }
        public string FavoriteColor { get; set; }
        public string FavoriteFood { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace welcome_to_web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/APIController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using welcome_to_web.Models;

namespace welcome_to_web.Controllers
{
    public class APIController : Controller
    {
        [Route("/api")]
        public IActionResult API()
        {
            var jake = new APIModel{
                Name = "Jake",
                FavoriteColor = "Black",
                FavoriteFood = "Pizza"
            };
            return Json(jake);
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/FirstController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using welcome_to_web.Models;

namespace welcome_to_web.Controllers
{
    public class FirstController : Controller
    {
         [Route("/First")]
        public IActionResult First()
        {
            ViewData["Message"] = "Hello World!";
            return View();
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using welcome_to_web.Models;

namespace welcome_to_web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MailingListController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using welcome_to_web.Models;
using System.IO;


namespace welcome_to_web.Controllers
{
    public class MailingListController : Controller
    {
        public IActionResult Index()
        {
            var contacts = new Dictionary<string, string>();
            using (var reader = new StreamReader(System.IO.File.Open("emails.csv", FileMode.Open)))
                while (reader.Peek() >= 0)
                {
                    var user = reader.ReadLine();
                    var data = user.Split(',');
                    for (int i = 0; i < data.Length; i++)
                    {
                        if (contacts.ContainsKey(data[i]) == false && contacts.ContainsValue(data[i]) == false)
                            contacts.Add(data[i], data[i + 1]);
                    }
                }
            return View(contacts);
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SubscribeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using welcome_to_web.Models;
using System.IO;


namespace welcome_to_web.Controllers
{
    public class SubscribeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(string name, string email)
        {
            ViewData["name"] = name;
            ViewData["email"] = email;
            using ( var writer = new StreamWriter(System.IO.File.Open($"emails.csv",FileMode.Append)))
            {
                writer.WriteLine($"{name},{email}");
            }
            return View();
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserIDController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using welcome_to_web.Models;

namespace welcome_to_web.Controllers
{
    public class UserIDController : Controller
    {
        [Route("/UserID/{id}")]
        public IActionResult UserID()
        {
            
            return View();
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/First/First.cshtml
@{
    ViewData["Title"] = "First";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
<h2>WELCOME TO MY AWESOME WEBSITE! </h2>
<h4> Click any of the links above to do awesome things.</h4>
<ul> 
    <li> /First - brings you to a page that says Hello World!</li>
    <li> /api - returns a json object </li>
    <li>/user/{id} will return a fake profile page for the user id that was passed in</li>
    <li>/subscribe will show a form that posts to the URL /subscribe, and will also POST which will append the incoming email from the body to a file called emails.csv</li>
    <li>/mailinglist will show all the emails in the emails.csv</li>
</ul>
</div>

Views/MailingList/Index.cshtml
@{
    ViewData["Title"] = "Mailing List";
}
<h1>@ViewData["Title"]</h1>
<h2>Here are the people who are subscribed</h2>
<div>
    
    @model Dictionary<string,string>
@foreach (var person in Model)
{
    <p>Name: @person.Key : Email: @person.Value</p>
}

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - welcome_to_web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">welcome_to_web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="First" asp-action="First">First</a></li>
                    <li><a asp-area="" asp-controller="API" asp-action="Api">API</a></li>
                    <li><a asp-area="" asp-controller="UserID" asp-action="99">User ID:99</a></li>
                    <li><a asp-area="" asp-controller="Subscribe" asp-action="">Subscribe</a></li>
                    <li><a asp-area="" asp-controller="MailingList" asp-action="">Mailing List</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - welcome_to_web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Subscribe/index.cshtml
@{
    ViewData["Title"] = "Subscribe";
}
<h2>Subscribe to us below!</h2>
<div>
<form asp-controller="Subscribe" asp-action="Index" method="post">
    Name: <input type="text" name = "name" /><br />
    Email:  <input type="email" name = "email" /> <br />
    <button type="submit">Register</button>
</form>
</div>
<div>
    <p> @ViewData["name"] </p>
    <p>@ViewData["email"]</p>

Views/UserID/UserID.cshtml
@{
    ViewData["Title"] = "Profile Page";
}
<h2>@ViewData["Title"]</h2>
<h3>Here is the profile page for User ID: @ViewContext.RouteData.Values["id"]</h3>
<p> Name: John Doe </p>
<p> Rank: Captain </p>
<p> Serial Number: 12345 </p>
<p> Speciality: Mage comp in HotS </p>